// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    BoardCard: typeof import('./src/components/BoardCard.vue')['default']
    BoardDragAndDrop: typeof import('./src/components/BoardDragAndDrop.vue')['default']
    ImageDropzone: typeof import('./src/components/ImageDropzone.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
    TaskCreator: typeof import('./src/components/TaskCreator.vue')['default']
    Templates: typeof import('./src/components/TaskCreator.vue')['default']
  }
}

export {}
